universe = vanilla
getenv = True
transfer_input_files = /a/home/cc/cs/itamares/Projects/ibdadmixed/scripts/htcondor.py,$(job_files)
requirements = Machine == "rack-bio-eran-01.cs.tau.ac.il" || Machine == "rack-bio-eran-03.cs.tau.ac.il" || Machine == "rack-bio-eran-04.cs.tau.ac.il" || Machine == "rack-bio-eran-05.cs.tau.ac.il" || Machine == "rack-bio-eran-06.cs.tau.ac.il" || Machine == "rack-bio-eran-07.cs.tau.ac.il" || Machine == "rack-bio-eran-08.cs.tau.ac.il" || Machine == "rack-bio-eran-13.cs.tau.ac.il" || Machine == "rack-bio-eran-17.cs.tau.ac.il" || Machine == "rack-bio-eran-18.cs.tau.ac.il" || Machine == "rack-bio-eran-20.cs.tau.ac.il" || Machine == "rack-bio-eran-21.cs.tau.ac.il" || Machine == "rack-bio-eran-22.cs.tau.ac.il"
Rank = Memory
queue $(processes)
